name: slide_rating_dialog
description: Introducing the Slide Rating Dialog, a customizable and interactive widget for collecting user ratings.
version: 1.0.4
repository: https://github.com/Zee604/slide_rating_dialog.git

environment:
  sdk: ^3.0.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0



flutter:
  assets:
    - assets/images/

platforms:
  android:
  ios: